//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace ViewModel.wcf_ChuDe {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clientmodel_HinhAnh", Namespace="http://schemas.datacontract.org/2004/07/LCTMoodle.WebServices.Client_Model")]
    public partial class clientmodel_HinhAnh : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int _ChiSoField;
        
        private byte[] _HinhAnhField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _ChiSo {
            get {
                return this._ChiSoField;
            }
            set {
                if ((this._ChiSoField.Equals(value) != true)) {
                    this._ChiSoField = value;
                    this.RaisePropertyChanged("_ChiSo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] _HinhAnh {
            get {
                return this._HinhAnhField;
            }
            set {
                if ((object.ReferenceEquals(this._HinhAnhField, value) != true)) {
                    this._HinhAnhField = value;
                    this.RaisePropertyChanged("_HinhAnh");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTO", Namespace="http://schemas.datacontract.org/2004/07/DTOLayer")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ViewModel.wcf_ChuDe.TapTinDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ViewModel.wcf_ChuDe.NguoiDungDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ViewModel.wcf_ChuDe.ChuDeDTO))]
    public partial class DTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.Generic.Dictionary<string, object> duLieuThemField;
        
        private System.Nullable<int> maField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, object> duLieuThem {
            get {
                return this.duLieuThemField;
            }
            set {
                if ((object.ReferenceEquals(this.duLieuThemField, value) != true)) {
                    this.duLieuThemField = value;
                    this.RaisePropertyChanged("duLieuThem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ma {
            get {
                return this.maField;
            }
            set {
                if ((this.maField.Equals(value) != true)) {
                    this.maField = value;
                    this.RaisePropertyChanged("ma");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TapTinDTO", Namespace="http://schemas.datacontract.org/2004/07/DTOLayer")]
    public partial class TapTinDTO : ViewModel.wcf_ChuDe.DTO {
        
        private string duoiField;
        
        private string loaiField;
        
        private ViewModel.wcf_ChuDe.NguoiDungDTO nguoiTaoField;
        
        private string tenField;
        
        private System.Nullable<System.DateTime> thoiDiemTaoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string duoi {
            get {
                return this.duoiField;
            }
            set {
                if ((object.ReferenceEquals(this.duoiField, value) != true)) {
                    this.duoiField = value;
                    this.RaisePropertyChanged("duoi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string loai {
            get {
                return this.loaiField;
            }
            set {
                if ((object.ReferenceEquals(this.loaiField, value) != true)) {
                    this.loaiField = value;
                    this.RaisePropertyChanged("loai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ViewModel.wcf_ChuDe.NguoiDungDTO nguoiTao {
            get {
                return this.nguoiTaoField;
            }
            set {
                if ((object.ReferenceEquals(this.nguoiTaoField, value) != true)) {
                    this.nguoiTaoField = value;
                    this.RaisePropertyChanged("nguoiTao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ten {
            get {
                return this.tenField;
            }
            set {
                if ((object.ReferenceEquals(this.tenField, value) != true)) {
                    this.tenField = value;
                    this.RaisePropertyChanged("ten");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> thoiDiemTao {
            get {
                return this.thoiDiemTaoField;
            }
            set {
                if ((this.thoiDiemTaoField.Equals(value) != true)) {
                    this.thoiDiemTaoField = value;
                    this.RaisePropertyChanged("thoiDiemTao");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NguoiDungDTO", Namespace="http://schemas.datacontract.org/2004/07/DTOLayer")]
    public partial class NguoiDungDTO : ViewModel.wcf_ChuDe.DTO {
        
        private string diaChiField;
        
        private System.Nullable<int> diemHoiDapField;
        
        private string emailField;
        
        private System.Nullable<int> gioiTinhField;
        
        private ViewModel.wcf_ChuDe.TapTinDTO hinhDaiDienField;
        
        private string hoField;
        
        private string maKichHoatField;
        
        private string matKhauField;
        
        private string matKhauCap2Field;
        
        private System.Nullable<System.DateTime> ngaySinhField;
        
        private string soDienThoaiField;
        
        private string tenField;
        
        private string tenLotField;
        
        private string tenTaiKhoanField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string diaChi {
            get {
                return this.diaChiField;
            }
            set {
                if ((object.ReferenceEquals(this.diaChiField, value) != true)) {
                    this.diaChiField = value;
                    this.RaisePropertyChanged("diaChi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> diemHoiDap {
            get {
                return this.diemHoiDapField;
            }
            set {
                if ((this.diemHoiDapField.Equals(value) != true)) {
                    this.diemHoiDapField = value;
                    this.RaisePropertyChanged("diemHoiDap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> gioiTinh {
            get {
                return this.gioiTinhField;
            }
            set {
                if ((this.gioiTinhField.Equals(value) != true)) {
                    this.gioiTinhField = value;
                    this.RaisePropertyChanged("gioiTinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ViewModel.wcf_ChuDe.TapTinDTO hinhDaiDien {
            get {
                return this.hinhDaiDienField;
            }
            set {
                if ((object.ReferenceEquals(this.hinhDaiDienField, value) != true)) {
                    this.hinhDaiDienField = value;
                    this.RaisePropertyChanged("hinhDaiDien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ho {
            get {
                return this.hoField;
            }
            set {
                if ((object.ReferenceEquals(this.hoField, value) != true)) {
                    this.hoField = value;
                    this.RaisePropertyChanged("ho");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maKichHoat {
            get {
                return this.maKichHoatField;
            }
            set {
                if ((object.ReferenceEquals(this.maKichHoatField, value) != true)) {
                    this.maKichHoatField = value;
                    this.RaisePropertyChanged("maKichHoat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string matKhau {
            get {
                return this.matKhauField;
            }
            set {
                if ((object.ReferenceEquals(this.matKhauField, value) != true)) {
                    this.matKhauField = value;
                    this.RaisePropertyChanged("matKhau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string matKhauCap2 {
            get {
                return this.matKhauCap2Field;
            }
            set {
                if ((object.ReferenceEquals(this.matKhauCap2Field, value) != true)) {
                    this.matKhauCap2Field = value;
                    this.RaisePropertyChanged("matKhauCap2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ngaySinh {
            get {
                return this.ngaySinhField;
            }
            set {
                if ((this.ngaySinhField.Equals(value) != true)) {
                    this.ngaySinhField = value;
                    this.RaisePropertyChanged("ngaySinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string soDienThoai {
            get {
                return this.soDienThoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.soDienThoaiField, value) != true)) {
                    this.soDienThoaiField = value;
                    this.RaisePropertyChanged("soDienThoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ten {
            get {
                return this.tenField;
            }
            set {
                if ((object.ReferenceEquals(this.tenField, value) != true)) {
                    this.tenField = value;
                    this.RaisePropertyChanged("ten");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tenLot {
            get {
                return this.tenLotField;
            }
            set {
                if ((object.ReferenceEquals(this.tenLotField, value) != true)) {
                    this.tenLotField = value;
                    this.RaisePropertyChanged("tenLot");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tenTaiKhoan {
            get {
                return this.tenTaiKhoanField;
            }
            set {
                if ((object.ReferenceEquals(this.tenTaiKhoanField, value) != true)) {
                    this.tenTaiKhoanField = value;
                    this.RaisePropertyChanged("tenTaiKhoan");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChuDeDTO", Namespace="http://schemas.datacontract.org/2004/07/DTOLayer")]
    public partial class ChuDeDTO : ViewModel.wcf_ChuDe.DTO {
        
        private ViewModel.wcf_ChuDe.ChuDeDTO chaField;
        
        private System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_ChuDe.ChuDeDTO> conField;
        
        private ViewModel.wcf_ChuDe.TapTinDTO hinhDaiDienField;
        
        private string moTaField;
        
        private ViewModel.wcf_ChuDe.NguoiDungDTO nguoiTaoField;
        
        private string tenField;
        
        private System.Nullable<System.DateTime> thoiDiemTaoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ViewModel.wcf_ChuDe.ChuDeDTO cha {
            get {
                return this.chaField;
            }
            set {
                if ((object.ReferenceEquals(this.chaField, value) != true)) {
                    this.chaField = value;
                    this.RaisePropertyChanged("cha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_ChuDe.ChuDeDTO> con {
            get {
                return this.conField;
            }
            set {
                if ((object.ReferenceEquals(this.conField, value) != true)) {
                    this.conField = value;
                    this.RaisePropertyChanged("con");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ViewModel.wcf_ChuDe.TapTinDTO hinhDaiDien {
            get {
                return this.hinhDaiDienField;
            }
            set {
                if ((object.ReferenceEquals(this.hinhDaiDienField, value) != true)) {
                    this.hinhDaiDienField = value;
                    this.RaisePropertyChanged("hinhDaiDien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string moTa {
            get {
                return this.moTaField;
            }
            set {
                if ((object.ReferenceEquals(this.moTaField, value) != true)) {
                    this.moTaField = value;
                    this.RaisePropertyChanged("moTa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ViewModel.wcf_ChuDe.NguoiDungDTO nguoiTao {
            get {
                return this.nguoiTaoField;
            }
            set {
                if ((object.ReferenceEquals(this.nguoiTaoField, value) != true)) {
                    this.nguoiTaoField = value;
                    this.RaisePropertyChanged("nguoiTao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ten {
            get {
                return this.tenField;
            }
            set {
                if ((object.ReferenceEquals(this.tenField, value) != true)) {
                    this.tenField = value;
                    this.RaisePropertyChanged("ten");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> thoiDiemTao {
            get {
                return this.thoiDiemTaoField;
            }
            set {
                if ((this.thoiDiemTaoField.Equals(value) != true)) {
                    this.thoiDiemTaoField = value;
                    this.RaisePropertyChanged("thoiDiemTao");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wcf_ChuDe.Iwcf_ChuDe")]
    public interface Iwcf_ChuDe {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Iwcf_ChuDe/layHinhAnh", ReplyAction="http://tempuri.org/Iwcf_ChuDe/layHinhAnhResponse")]
        System.IAsyncResult BeginlayHinhAnh(string _Ten, System.AsyncCallback callback, object asyncState);
        
        byte[] EndlayHinhAnh(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Iwcf_ChuDe/layHinhAnhChiSo", ReplyAction="http://tempuri.org/Iwcf_ChuDe/layHinhAnhChiSoResponse")]
        System.IAsyncResult BeginlayHinhAnhChiSo(int _ChiSo, string _Ten, System.AsyncCallback callback, object asyncState);
        
        ViewModel.wcf_ChuDe.clientmodel_HinhAnh EndlayHinhAnhChiSo(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Iwcf_ChuDe/layTheoMa", ReplyAction="http://tempuri.org/Iwcf_ChuDe/layTheoMaResponse")]
        System.IAsyncResult BeginlayTheoMa(int _Ma, System.AsyncCallback callback, object asyncState);
        
        ViewModel.wcf_ChuDe.ChuDeDTO EndlayTheoMa(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Iwcf_ChuDe/layTheoMaCha", ReplyAction="http://tempuri.org/Iwcf_ChuDe/layTheoMaChaResponse")]
        System.IAsyncResult BeginlayTheoMaCha(int _MaChuDeCha, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_ChuDe.ChuDeDTO> EndlayTheoMaCha(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Iwcf_ChuDe/timKiem", ReplyAction="http://tempuri.org/Iwcf_ChuDe/timKiemResponse")]
        System.IAsyncResult BegintimKiem(string _TuKhoa, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_ChuDe.ChuDeDTO> EndtimKiem(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Iwcf_ChuDeChannel : ViewModel.wcf_ChuDe.Iwcf_ChuDe, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class layHinhAnhCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public layHinhAnhCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public byte[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class layHinhAnhChiSoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public layHinhAnhChiSoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ViewModel.wcf_ChuDe.clientmodel_HinhAnh Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ViewModel.wcf_ChuDe.clientmodel_HinhAnh)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class layTheoMaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public layTheoMaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ViewModel.wcf_ChuDe.ChuDeDTO Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ViewModel.wcf_ChuDe.ChuDeDTO)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class layTheoMaChaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public layTheoMaChaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_ChuDe.ChuDeDTO> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_ChuDe.ChuDeDTO>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class timKiemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public timKiemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_ChuDe.ChuDeDTO> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_ChuDe.ChuDeDTO>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Iwcf_ChuDeClient : System.ServiceModel.ClientBase<ViewModel.wcf_ChuDe.Iwcf_ChuDe>, ViewModel.wcf_ChuDe.Iwcf_ChuDe {
        
        private BeginOperationDelegate onBeginlayHinhAnhDelegate;
        
        private EndOperationDelegate onEndlayHinhAnhDelegate;
        
        private System.Threading.SendOrPostCallback onlayHinhAnhCompletedDelegate;
        
        private BeginOperationDelegate onBeginlayHinhAnhChiSoDelegate;
        
        private EndOperationDelegate onEndlayHinhAnhChiSoDelegate;
        
        private System.Threading.SendOrPostCallback onlayHinhAnhChiSoCompletedDelegate;
        
        private BeginOperationDelegate onBeginlayTheoMaDelegate;
        
        private EndOperationDelegate onEndlayTheoMaDelegate;
        
        private System.Threading.SendOrPostCallback onlayTheoMaCompletedDelegate;
        
        private BeginOperationDelegate onBeginlayTheoMaChaDelegate;
        
        private EndOperationDelegate onEndlayTheoMaChaDelegate;
        
        private System.Threading.SendOrPostCallback onlayTheoMaChaCompletedDelegate;
        
        private BeginOperationDelegate onBegintimKiemDelegate;
        
        private EndOperationDelegate onEndtimKiemDelegate;
        
        private System.Threading.SendOrPostCallback ontimKiemCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public Iwcf_ChuDeClient() {
        }
        
        public Iwcf_ChuDeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Iwcf_ChuDeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Iwcf_ChuDeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Iwcf_ChuDeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<layHinhAnhCompletedEventArgs> layHinhAnhCompleted;
        
        public event System.EventHandler<layHinhAnhChiSoCompletedEventArgs> layHinhAnhChiSoCompleted;
        
        public event System.EventHandler<layTheoMaCompletedEventArgs> layTheoMaCompleted;
        
        public event System.EventHandler<layTheoMaChaCompletedEventArgs> layTheoMaChaCompleted;
        
        public event System.EventHandler<timKiemCompletedEventArgs> timKiemCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ViewModel.wcf_ChuDe.Iwcf_ChuDe.BeginlayHinhAnh(string _Ten, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginlayHinhAnh(_Ten, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        byte[] ViewModel.wcf_ChuDe.Iwcf_ChuDe.EndlayHinhAnh(System.IAsyncResult result) {
            return base.Channel.EndlayHinhAnh(result);
        }
        
        private System.IAsyncResult OnBeginlayHinhAnh(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string _Ten = ((string)(inValues[0]));
            return ((ViewModel.wcf_ChuDe.Iwcf_ChuDe)(this)).BeginlayHinhAnh(_Ten, callback, asyncState);
        }
        
        private object[] OnEndlayHinhAnh(System.IAsyncResult result) {
            byte[] retVal = ((ViewModel.wcf_ChuDe.Iwcf_ChuDe)(this)).EndlayHinhAnh(result);
            return new object[] {
                    retVal};
        }
        
        private void OnlayHinhAnhCompleted(object state) {
            if ((this.layHinhAnhCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.layHinhAnhCompleted(this, new layHinhAnhCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void layHinhAnhAsync(string _Ten) {
            this.layHinhAnhAsync(_Ten, null);
        }
        
        public void layHinhAnhAsync(string _Ten, object userState) {
            if ((this.onBeginlayHinhAnhDelegate == null)) {
                this.onBeginlayHinhAnhDelegate = new BeginOperationDelegate(this.OnBeginlayHinhAnh);
            }
            if ((this.onEndlayHinhAnhDelegate == null)) {
                this.onEndlayHinhAnhDelegate = new EndOperationDelegate(this.OnEndlayHinhAnh);
            }
            if ((this.onlayHinhAnhCompletedDelegate == null)) {
                this.onlayHinhAnhCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnlayHinhAnhCompleted);
            }
            base.InvokeAsync(this.onBeginlayHinhAnhDelegate, new object[] {
                        _Ten}, this.onEndlayHinhAnhDelegate, this.onlayHinhAnhCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ViewModel.wcf_ChuDe.Iwcf_ChuDe.BeginlayHinhAnhChiSo(int _ChiSo, string _Ten, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginlayHinhAnhChiSo(_ChiSo, _Ten, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ViewModel.wcf_ChuDe.clientmodel_HinhAnh ViewModel.wcf_ChuDe.Iwcf_ChuDe.EndlayHinhAnhChiSo(System.IAsyncResult result) {
            return base.Channel.EndlayHinhAnhChiSo(result);
        }
        
        private System.IAsyncResult OnBeginlayHinhAnhChiSo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int _ChiSo = ((int)(inValues[0]));
            string _Ten = ((string)(inValues[1]));
            return ((ViewModel.wcf_ChuDe.Iwcf_ChuDe)(this)).BeginlayHinhAnhChiSo(_ChiSo, _Ten, callback, asyncState);
        }
        
        private object[] OnEndlayHinhAnhChiSo(System.IAsyncResult result) {
            ViewModel.wcf_ChuDe.clientmodel_HinhAnh retVal = ((ViewModel.wcf_ChuDe.Iwcf_ChuDe)(this)).EndlayHinhAnhChiSo(result);
            return new object[] {
                    retVal};
        }
        
        private void OnlayHinhAnhChiSoCompleted(object state) {
            if ((this.layHinhAnhChiSoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.layHinhAnhChiSoCompleted(this, new layHinhAnhChiSoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void layHinhAnhChiSoAsync(int _ChiSo, string _Ten) {
            this.layHinhAnhChiSoAsync(_ChiSo, _Ten, null);
        }
        
        public void layHinhAnhChiSoAsync(int _ChiSo, string _Ten, object userState) {
            if ((this.onBeginlayHinhAnhChiSoDelegate == null)) {
                this.onBeginlayHinhAnhChiSoDelegate = new BeginOperationDelegate(this.OnBeginlayHinhAnhChiSo);
            }
            if ((this.onEndlayHinhAnhChiSoDelegate == null)) {
                this.onEndlayHinhAnhChiSoDelegate = new EndOperationDelegate(this.OnEndlayHinhAnhChiSo);
            }
            if ((this.onlayHinhAnhChiSoCompletedDelegate == null)) {
                this.onlayHinhAnhChiSoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnlayHinhAnhChiSoCompleted);
            }
            base.InvokeAsync(this.onBeginlayHinhAnhChiSoDelegate, new object[] {
                        _ChiSo,
                        _Ten}, this.onEndlayHinhAnhChiSoDelegate, this.onlayHinhAnhChiSoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ViewModel.wcf_ChuDe.Iwcf_ChuDe.BeginlayTheoMa(int _Ma, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginlayTheoMa(_Ma, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ViewModel.wcf_ChuDe.ChuDeDTO ViewModel.wcf_ChuDe.Iwcf_ChuDe.EndlayTheoMa(System.IAsyncResult result) {
            return base.Channel.EndlayTheoMa(result);
        }
        
        private System.IAsyncResult OnBeginlayTheoMa(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int _Ma = ((int)(inValues[0]));
            return ((ViewModel.wcf_ChuDe.Iwcf_ChuDe)(this)).BeginlayTheoMa(_Ma, callback, asyncState);
        }
        
        private object[] OnEndlayTheoMa(System.IAsyncResult result) {
            ViewModel.wcf_ChuDe.ChuDeDTO retVal = ((ViewModel.wcf_ChuDe.Iwcf_ChuDe)(this)).EndlayTheoMa(result);
            return new object[] {
                    retVal};
        }
        
        private void OnlayTheoMaCompleted(object state) {
            if ((this.layTheoMaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.layTheoMaCompleted(this, new layTheoMaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void layTheoMaAsync(int _Ma) {
            this.layTheoMaAsync(_Ma, null);
        }
        
        public void layTheoMaAsync(int _Ma, object userState) {
            if ((this.onBeginlayTheoMaDelegate == null)) {
                this.onBeginlayTheoMaDelegate = new BeginOperationDelegate(this.OnBeginlayTheoMa);
            }
            if ((this.onEndlayTheoMaDelegate == null)) {
                this.onEndlayTheoMaDelegate = new EndOperationDelegate(this.OnEndlayTheoMa);
            }
            if ((this.onlayTheoMaCompletedDelegate == null)) {
                this.onlayTheoMaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnlayTheoMaCompleted);
            }
            base.InvokeAsync(this.onBeginlayTheoMaDelegate, new object[] {
                        _Ma}, this.onEndlayTheoMaDelegate, this.onlayTheoMaCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ViewModel.wcf_ChuDe.Iwcf_ChuDe.BeginlayTheoMaCha(int _MaChuDeCha, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginlayTheoMaCha(_MaChuDeCha, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_ChuDe.ChuDeDTO> ViewModel.wcf_ChuDe.Iwcf_ChuDe.EndlayTheoMaCha(System.IAsyncResult result) {
            return base.Channel.EndlayTheoMaCha(result);
        }
        
        private System.IAsyncResult OnBeginlayTheoMaCha(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int _MaChuDeCha = ((int)(inValues[0]));
            return ((ViewModel.wcf_ChuDe.Iwcf_ChuDe)(this)).BeginlayTheoMaCha(_MaChuDeCha, callback, asyncState);
        }
        
        private object[] OnEndlayTheoMaCha(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_ChuDe.ChuDeDTO> retVal = ((ViewModel.wcf_ChuDe.Iwcf_ChuDe)(this)).EndlayTheoMaCha(result);
            return new object[] {
                    retVal};
        }
        
        private void OnlayTheoMaChaCompleted(object state) {
            if ((this.layTheoMaChaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.layTheoMaChaCompleted(this, new layTheoMaChaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void layTheoMaChaAsync(int _MaChuDeCha) {
            this.layTheoMaChaAsync(_MaChuDeCha, null);
        }
        
        public void layTheoMaChaAsync(int _MaChuDeCha, object userState) {
            if ((this.onBeginlayTheoMaChaDelegate == null)) {
                this.onBeginlayTheoMaChaDelegate = new BeginOperationDelegate(this.OnBeginlayTheoMaCha);
            }
            if ((this.onEndlayTheoMaChaDelegate == null)) {
                this.onEndlayTheoMaChaDelegate = new EndOperationDelegate(this.OnEndlayTheoMaCha);
            }
            if ((this.onlayTheoMaChaCompletedDelegate == null)) {
                this.onlayTheoMaChaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnlayTheoMaChaCompleted);
            }
            base.InvokeAsync(this.onBeginlayTheoMaChaDelegate, new object[] {
                        _MaChuDeCha}, this.onEndlayTheoMaChaDelegate, this.onlayTheoMaChaCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ViewModel.wcf_ChuDe.Iwcf_ChuDe.BegintimKiem(string _TuKhoa, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegintimKiem(_TuKhoa, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_ChuDe.ChuDeDTO> ViewModel.wcf_ChuDe.Iwcf_ChuDe.EndtimKiem(System.IAsyncResult result) {
            return base.Channel.EndtimKiem(result);
        }
        
        private System.IAsyncResult OnBegintimKiem(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string _TuKhoa = ((string)(inValues[0]));
            return ((ViewModel.wcf_ChuDe.Iwcf_ChuDe)(this)).BegintimKiem(_TuKhoa, callback, asyncState);
        }
        
        private object[] OnEndtimKiem(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_ChuDe.ChuDeDTO> retVal = ((ViewModel.wcf_ChuDe.Iwcf_ChuDe)(this)).EndtimKiem(result);
            return new object[] {
                    retVal};
        }
        
        private void OntimKiemCompleted(object state) {
            if ((this.timKiemCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.timKiemCompleted(this, new timKiemCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void timKiemAsync(string _TuKhoa) {
            this.timKiemAsync(_TuKhoa, null);
        }
        
        public void timKiemAsync(string _TuKhoa, object userState) {
            if ((this.onBegintimKiemDelegate == null)) {
                this.onBegintimKiemDelegate = new BeginOperationDelegate(this.OnBegintimKiem);
            }
            if ((this.onEndtimKiemDelegate == null)) {
                this.onEndtimKiemDelegate = new EndOperationDelegate(this.OnEndtimKiem);
            }
            if ((this.ontimKiemCompletedDelegate == null)) {
                this.ontimKiemCompletedDelegate = new System.Threading.SendOrPostCallback(this.OntimKiemCompleted);
            }
            base.InvokeAsync(this.onBegintimKiemDelegate, new object[] {
                        _TuKhoa}, this.onEndtimKiemDelegate, this.ontimKiemCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override ViewModel.wcf_ChuDe.Iwcf_ChuDe CreateChannel() {
            return new Iwcf_ChuDeClientChannel(this);
        }
        
        private class Iwcf_ChuDeClientChannel : ChannelBase<ViewModel.wcf_ChuDe.Iwcf_ChuDe>, ViewModel.wcf_ChuDe.Iwcf_ChuDe {
            
            public Iwcf_ChuDeClientChannel(System.ServiceModel.ClientBase<ViewModel.wcf_ChuDe.Iwcf_ChuDe> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginlayHinhAnh(string _Ten, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = _Ten;
                System.IAsyncResult _result = base.BeginInvoke("layHinhAnh", _args, callback, asyncState);
                return _result;
            }
            
            public byte[] EndlayHinhAnh(System.IAsyncResult result) {
                object[] _args = new object[0];
                byte[] _result = ((byte[])(base.EndInvoke("layHinhAnh", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginlayHinhAnhChiSo(int _ChiSo, string _Ten, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = _ChiSo;
                _args[1] = _Ten;
                System.IAsyncResult _result = base.BeginInvoke("layHinhAnhChiSo", _args, callback, asyncState);
                return _result;
            }
            
            public ViewModel.wcf_ChuDe.clientmodel_HinhAnh EndlayHinhAnhChiSo(System.IAsyncResult result) {
                object[] _args = new object[0];
                ViewModel.wcf_ChuDe.clientmodel_HinhAnh _result = ((ViewModel.wcf_ChuDe.clientmodel_HinhAnh)(base.EndInvoke("layHinhAnhChiSo", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginlayTheoMa(int _Ma, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = _Ma;
                System.IAsyncResult _result = base.BeginInvoke("layTheoMa", _args, callback, asyncState);
                return _result;
            }
            
            public ViewModel.wcf_ChuDe.ChuDeDTO EndlayTheoMa(System.IAsyncResult result) {
                object[] _args = new object[0];
                ViewModel.wcf_ChuDe.ChuDeDTO _result = ((ViewModel.wcf_ChuDe.ChuDeDTO)(base.EndInvoke("layTheoMa", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginlayTheoMaCha(int _MaChuDeCha, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = _MaChuDeCha;
                System.IAsyncResult _result = base.BeginInvoke("layTheoMaCha", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_ChuDe.ChuDeDTO> EndlayTheoMaCha(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_ChuDe.ChuDeDTO> _result = ((System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_ChuDe.ChuDeDTO>)(base.EndInvoke("layTheoMaCha", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegintimKiem(string _TuKhoa, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = _TuKhoa;
                System.IAsyncResult _result = base.BeginInvoke("timKiem", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_ChuDe.ChuDeDTO> EndtimKiem(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_ChuDe.ChuDeDTO> _result = ((System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_ChuDe.ChuDeDTO>)(base.EndInvoke("timKiem", _args, result)));
                return _result;
            }
        }
    }
}
