//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace ViewModel.wcf_KhoaHoc {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="clientmodel_HinhAnh", Namespace="http://schemas.datacontract.org/2004/07/LCTMoodle.WebServices.Client_Model")]
    public partial class clientmodel_HinhAnh : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int _ChiSoField;
        
        private byte[] _HinhAnhField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _ChiSo {
            get {
                return this._ChiSoField;
            }
            set {
                if ((this._ChiSoField.Equals(value) != true)) {
                    this._ChiSoField = value;
                    this.RaisePropertyChanged("_ChiSo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] _HinhAnh {
            get {
                return this._HinhAnhField;
            }
            set {
                if ((object.ReferenceEquals(this._HinhAnhField, value) != true)) {
                    this._HinhAnhField = value;
                    this.RaisePropertyChanged("_HinhAnh");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DTO", Namespace="http://schemas.datacontract.org/2004/07/DTOLayer")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ViewModel.wcf_KhoaHoc.ChuDeDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ViewModel.wcf_KhoaHoc.TapTinDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ViewModel.wcf_KhoaHoc.NguoiDungDTO))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ViewModel.wcf_KhoaHoc.KhoaHocDTO))]
    public partial class DTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.Generic.Dictionary<string, object> duLieuThemField;
        
        private System.Nullable<int> maField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, object> duLieuThem {
            get {
                return this.duLieuThemField;
            }
            set {
                if ((object.ReferenceEquals(this.duLieuThemField, value) != true)) {
                    this.duLieuThemField = value;
                    this.RaisePropertyChanged("duLieuThem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ma {
            get {
                return this.maField;
            }
            set {
                if ((this.maField.Equals(value) != true)) {
                    this.maField = value;
                    this.RaisePropertyChanged("ma");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChuDeDTO", Namespace="http://schemas.datacontract.org/2004/07/DTOLayer")]
    public partial class ChuDeDTO : ViewModel.wcf_KhoaHoc.DTO {
        
        private ViewModel.wcf_KhoaHoc.ChuDeDTO chaField;
        
        private System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.ChuDeDTO> conField;
        
        private ViewModel.wcf_KhoaHoc.TapTinDTO hinhDaiDienField;
        
        private string moTaField;
        
        private ViewModel.wcf_KhoaHoc.NguoiDungDTO nguoiTaoField;
        
        private string tenField;
        
        private System.Nullable<System.DateTime> thoiDiemTaoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ViewModel.wcf_KhoaHoc.ChuDeDTO cha {
            get {
                return this.chaField;
            }
            set {
                if ((object.ReferenceEquals(this.chaField, value) != true)) {
                    this.chaField = value;
                    this.RaisePropertyChanged("cha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.ChuDeDTO> con {
            get {
                return this.conField;
            }
            set {
                if ((object.ReferenceEquals(this.conField, value) != true)) {
                    this.conField = value;
                    this.RaisePropertyChanged("con");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ViewModel.wcf_KhoaHoc.TapTinDTO hinhDaiDien {
            get {
                return this.hinhDaiDienField;
            }
            set {
                if ((object.ReferenceEquals(this.hinhDaiDienField, value) != true)) {
                    this.hinhDaiDienField = value;
                    this.RaisePropertyChanged("hinhDaiDien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string moTa {
            get {
                return this.moTaField;
            }
            set {
                if ((object.ReferenceEquals(this.moTaField, value) != true)) {
                    this.moTaField = value;
                    this.RaisePropertyChanged("moTa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ViewModel.wcf_KhoaHoc.NguoiDungDTO nguoiTao {
            get {
                return this.nguoiTaoField;
            }
            set {
                if ((object.ReferenceEquals(this.nguoiTaoField, value) != true)) {
                    this.nguoiTaoField = value;
                    this.RaisePropertyChanged("nguoiTao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ten {
            get {
                return this.tenField;
            }
            set {
                if ((object.ReferenceEquals(this.tenField, value) != true)) {
                    this.tenField = value;
                    this.RaisePropertyChanged("ten");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> thoiDiemTao {
            get {
                return this.thoiDiemTaoField;
            }
            set {
                if ((this.thoiDiemTaoField.Equals(value) != true)) {
                    this.thoiDiemTaoField = value;
                    this.RaisePropertyChanged("thoiDiemTao");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TapTinDTO", Namespace="http://schemas.datacontract.org/2004/07/DTOLayer")]
    public partial class TapTinDTO : ViewModel.wcf_KhoaHoc.DTO {
        
        private string duoiField;
        
        private string loaiField;
        
        private ViewModel.wcf_KhoaHoc.NguoiDungDTO nguoiTaoField;
        
        private string tenField;
        
        private System.Nullable<System.DateTime> thoiDiemTaoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string duoi {
            get {
                return this.duoiField;
            }
            set {
                if ((object.ReferenceEquals(this.duoiField, value) != true)) {
                    this.duoiField = value;
                    this.RaisePropertyChanged("duoi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string loai {
            get {
                return this.loaiField;
            }
            set {
                if ((object.ReferenceEquals(this.loaiField, value) != true)) {
                    this.loaiField = value;
                    this.RaisePropertyChanged("loai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ViewModel.wcf_KhoaHoc.NguoiDungDTO nguoiTao {
            get {
                return this.nguoiTaoField;
            }
            set {
                if ((object.ReferenceEquals(this.nguoiTaoField, value) != true)) {
                    this.nguoiTaoField = value;
                    this.RaisePropertyChanged("nguoiTao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ten {
            get {
                return this.tenField;
            }
            set {
                if ((object.ReferenceEquals(this.tenField, value) != true)) {
                    this.tenField = value;
                    this.RaisePropertyChanged("ten");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> thoiDiemTao {
            get {
                return this.thoiDiemTaoField;
            }
            set {
                if ((this.thoiDiemTaoField.Equals(value) != true)) {
                    this.thoiDiemTaoField = value;
                    this.RaisePropertyChanged("thoiDiemTao");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NguoiDungDTO", Namespace="http://schemas.datacontract.org/2004/07/DTOLayer")]
    public partial class NguoiDungDTO : ViewModel.wcf_KhoaHoc.DTO {
        
        private string diaChiField;
        
        private System.Nullable<int> diemHoiDapField;
        
        private string emailField;
        
        private System.Nullable<int> gioiTinhField;
        
        private ViewModel.wcf_KhoaHoc.TapTinDTO hinhDaiDienField;
        
        private string hoField;
        
        private string maKichHoatField;
        
        private string matKhauField;
        
        private string matKhauCap2Field;
        
        private System.Nullable<System.DateTime> ngaySinhField;
        
        private string soDienThoaiField;
        
        private string tenField;
        
        private string tenLotField;
        
        private string tenTaiKhoanField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string diaChi {
            get {
                return this.diaChiField;
            }
            set {
                if ((object.ReferenceEquals(this.diaChiField, value) != true)) {
                    this.diaChiField = value;
                    this.RaisePropertyChanged("diaChi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> diemHoiDap {
            get {
                return this.diemHoiDapField;
            }
            set {
                if ((this.diemHoiDapField.Equals(value) != true)) {
                    this.diemHoiDapField = value;
                    this.RaisePropertyChanged("diemHoiDap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> gioiTinh {
            get {
                return this.gioiTinhField;
            }
            set {
                if ((this.gioiTinhField.Equals(value) != true)) {
                    this.gioiTinhField = value;
                    this.RaisePropertyChanged("gioiTinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ViewModel.wcf_KhoaHoc.TapTinDTO hinhDaiDien {
            get {
                return this.hinhDaiDienField;
            }
            set {
                if ((object.ReferenceEquals(this.hinhDaiDienField, value) != true)) {
                    this.hinhDaiDienField = value;
                    this.RaisePropertyChanged("hinhDaiDien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ho {
            get {
                return this.hoField;
            }
            set {
                if ((object.ReferenceEquals(this.hoField, value) != true)) {
                    this.hoField = value;
                    this.RaisePropertyChanged("ho");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maKichHoat {
            get {
                return this.maKichHoatField;
            }
            set {
                if ((object.ReferenceEquals(this.maKichHoatField, value) != true)) {
                    this.maKichHoatField = value;
                    this.RaisePropertyChanged("maKichHoat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string matKhau {
            get {
                return this.matKhauField;
            }
            set {
                if ((object.ReferenceEquals(this.matKhauField, value) != true)) {
                    this.matKhauField = value;
                    this.RaisePropertyChanged("matKhau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string matKhauCap2 {
            get {
                return this.matKhauCap2Field;
            }
            set {
                if ((object.ReferenceEquals(this.matKhauCap2Field, value) != true)) {
                    this.matKhauCap2Field = value;
                    this.RaisePropertyChanged("matKhauCap2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ngaySinh {
            get {
                return this.ngaySinhField;
            }
            set {
                if ((this.ngaySinhField.Equals(value) != true)) {
                    this.ngaySinhField = value;
                    this.RaisePropertyChanged("ngaySinh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string soDienThoai {
            get {
                return this.soDienThoaiField;
            }
            set {
                if ((object.ReferenceEquals(this.soDienThoaiField, value) != true)) {
                    this.soDienThoaiField = value;
                    this.RaisePropertyChanged("soDienThoai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ten {
            get {
                return this.tenField;
            }
            set {
                if ((object.ReferenceEquals(this.tenField, value) != true)) {
                    this.tenField = value;
                    this.RaisePropertyChanged("ten");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tenLot {
            get {
                return this.tenLotField;
            }
            set {
                if ((object.ReferenceEquals(this.tenLotField, value) != true)) {
                    this.tenLotField = value;
                    this.RaisePropertyChanged("tenLot");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tenTaiKhoan {
            get {
                return this.tenTaiKhoanField;
            }
            set {
                if ((object.ReferenceEquals(this.tenTaiKhoanField, value) != true)) {
                    this.tenTaiKhoanField = value;
                    this.RaisePropertyChanged("tenTaiKhoan");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KhoaHocDTO", Namespace="http://schemas.datacontract.org/2004/07/DTOLayer")]
    public partial class KhoaHocDTO : ViewModel.wcf_KhoaHoc.DTO {
        
        private bool canDangKyField;
        
        private bool canDuyetBaiVietField;
        
        private string cheDoRiengTuField;
        
        private ViewModel.wcf_KhoaHoc.ChuDeDTO chuDeField;
        
        private bool coBangDiemField;
        
        private bool coBangDiemDanhField;
        
        private System.Nullable<System.DateTime> hanDangKyField;
        
        private ViewModel.wcf_KhoaHoc.TapTinDTO hinhDaiDienField;
        
        private string moTaField;
        
        private ViewModel.wcf_KhoaHoc.NguoiDungDTO nguoiTaoField;
        
        private System.Nullable<int> phiThamGiaField;
        
        private string tenField;
        
        private System.Nullable<System.DateTime> thoiDiemHetHanField;
        
        private System.Nullable<System.DateTime> thoiDiemTaoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool canDangKy {
            get {
                return this.canDangKyField;
            }
            set {
                if ((this.canDangKyField.Equals(value) != true)) {
                    this.canDangKyField = value;
                    this.RaisePropertyChanged("canDangKy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool canDuyetBaiViet {
            get {
                return this.canDuyetBaiVietField;
            }
            set {
                if ((this.canDuyetBaiVietField.Equals(value) != true)) {
                    this.canDuyetBaiVietField = value;
                    this.RaisePropertyChanged("canDuyetBaiViet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cheDoRiengTu {
            get {
                return this.cheDoRiengTuField;
            }
            set {
                if ((object.ReferenceEquals(this.cheDoRiengTuField, value) != true)) {
                    this.cheDoRiengTuField = value;
                    this.RaisePropertyChanged("cheDoRiengTu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ViewModel.wcf_KhoaHoc.ChuDeDTO chuDe {
            get {
                return this.chuDeField;
            }
            set {
                if ((object.ReferenceEquals(this.chuDeField, value) != true)) {
                    this.chuDeField = value;
                    this.RaisePropertyChanged("chuDe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool coBangDiem {
            get {
                return this.coBangDiemField;
            }
            set {
                if ((this.coBangDiemField.Equals(value) != true)) {
                    this.coBangDiemField = value;
                    this.RaisePropertyChanged("coBangDiem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool coBangDiemDanh {
            get {
                return this.coBangDiemDanhField;
            }
            set {
                if ((this.coBangDiemDanhField.Equals(value) != true)) {
                    this.coBangDiemDanhField = value;
                    this.RaisePropertyChanged("coBangDiemDanh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> hanDangKy {
            get {
                return this.hanDangKyField;
            }
            set {
                if ((this.hanDangKyField.Equals(value) != true)) {
                    this.hanDangKyField = value;
                    this.RaisePropertyChanged("hanDangKy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ViewModel.wcf_KhoaHoc.TapTinDTO hinhDaiDien {
            get {
                return this.hinhDaiDienField;
            }
            set {
                if ((object.ReferenceEquals(this.hinhDaiDienField, value) != true)) {
                    this.hinhDaiDienField = value;
                    this.RaisePropertyChanged("hinhDaiDien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string moTa {
            get {
                return this.moTaField;
            }
            set {
                if ((object.ReferenceEquals(this.moTaField, value) != true)) {
                    this.moTaField = value;
                    this.RaisePropertyChanged("moTa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ViewModel.wcf_KhoaHoc.NguoiDungDTO nguoiTao {
            get {
                return this.nguoiTaoField;
            }
            set {
                if ((object.ReferenceEquals(this.nguoiTaoField, value) != true)) {
                    this.nguoiTaoField = value;
                    this.RaisePropertyChanged("nguoiTao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> phiThamGia {
            get {
                return this.phiThamGiaField;
            }
            set {
                if ((this.phiThamGiaField.Equals(value) != true)) {
                    this.phiThamGiaField = value;
                    this.RaisePropertyChanged("phiThamGia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ten {
            get {
                return this.tenField;
            }
            set {
                if ((object.ReferenceEquals(this.tenField, value) != true)) {
                    this.tenField = value;
                    this.RaisePropertyChanged("ten");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> thoiDiemHetHan {
            get {
                return this.thoiDiemHetHanField;
            }
            set {
                if ((this.thoiDiemHetHanField.Equals(value) != true)) {
                    this.thoiDiemHetHanField = value;
                    this.RaisePropertyChanged("thoiDiemHetHan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> thoiDiemTao {
            get {
                return this.thoiDiemTaoField;
            }
            set {
                if ((this.thoiDiemTaoField.Equals(value) != true)) {
                    this.thoiDiemTaoField = value;
                    this.RaisePropertyChanged("thoiDiemTao");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wcf_KhoaHoc.Iwcf_KhoaHoc")]
    public interface Iwcf_KhoaHoc {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Iwcf_KhoaHoc/layHinhAnh", ReplyAction="http://tempuri.org/Iwcf_KhoaHoc/layHinhAnhResponse")]
        System.IAsyncResult BeginlayHinhAnh(string _Ten, System.AsyncCallback callback, object asyncState);
        
        byte[] EndlayHinhAnh(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Iwcf_KhoaHoc/layHinhAnhChiSo", ReplyAction="http://tempuri.org/Iwcf_KhoaHoc/layHinhAnhChiSoResponse")]
        System.IAsyncResult BeginlayHinhAnhChiSo(int _ChiSo, string _Ten, System.AsyncCallback callback, object asyncState);
        
        ViewModel.wcf_KhoaHoc.clientmodel_HinhAnh EndlayHinhAnhChiSo(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Iwcf_KhoaHoc/layTheoMa", ReplyAction="http://tempuri.org/Iwcf_KhoaHoc/layTheoMaResponse")]
        System.IAsyncResult BeginlayTheoMa(int _Ma, System.AsyncCallback callback, object asyncState);
        
        ViewModel.wcf_KhoaHoc.KhoaHocDTO EndlayTheoMa(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Iwcf_KhoaHoc/lay", ReplyAction="http://tempuri.org/Iwcf_KhoaHoc/layResponse")]
        System.IAsyncResult Beginlay(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.KhoaHocDTO> Endlay(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Iwcf_KhoaHoc/layTheoMaChuDe", ReplyAction="http://tempuri.org/Iwcf_KhoaHoc/layTheoMaChuDeResponse")]
        System.IAsyncResult BeginlayTheoMaChuDe(int _MaChuDe, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.KhoaHocDTO> EndlayTheoMaChuDe(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Iwcf_KhoaHoc/layTheoMaNguoiDung", ReplyAction="http://tempuri.org/Iwcf_KhoaHoc/layTheoMaNguoiDungResponse")]
        System.IAsyncResult BeginlayTheoMaNguoiDung(int _MaNguoiDung, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.KhoaHocDTO> EndlayTheoMaNguoiDung(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Iwcf_KhoaHoc/layTheoMaNguoiDungVaTrangThai", ReplyAction="http://tempuri.org/Iwcf_KhoaHoc/layTheoMaNguoiDungVaTrangThaiResponse")]
        System.IAsyncResult BeginlayTheoMaNguoiDungVaTrangThai(int _MaNguoiDung, int _TrangThai, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.KhoaHocDTO> EndlayTheoMaNguoiDungVaTrangThai(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Iwcf_KhoaHoc/timKiem", ReplyAction="http://tempuri.org/Iwcf_KhoaHoc/timKiemResponse")]
        System.IAsyncResult BegintimKiem(string _TuKhoa, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.KhoaHocDTO> EndtimKiem(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Iwcf_KhoaHoc/timKiemTheoMaChuDe", ReplyAction="http://tempuri.org/Iwcf_KhoaHoc/timKiemTheoMaChuDeResponse")]
        System.IAsyncResult BegintimKiemTheoMaChuDe(int _MaChuDe, string _TuKhoa, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.KhoaHocDTO> EndtimKiemTheoMaChuDe(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Iwcf_KhoaHocChannel : ViewModel.wcf_KhoaHoc.Iwcf_KhoaHoc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class layHinhAnhCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public layHinhAnhCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public byte[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class layHinhAnhChiSoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public layHinhAnhChiSoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ViewModel.wcf_KhoaHoc.clientmodel_HinhAnh Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ViewModel.wcf_KhoaHoc.clientmodel_HinhAnh)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class layTheoMaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public layTheoMaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public ViewModel.wcf_KhoaHoc.KhoaHocDTO Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((ViewModel.wcf_KhoaHoc.KhoaHocDTO)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class layCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public layCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.KhoaHocDTO> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.KhoaHocDTO>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class layTheoMaChuDeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public layTheoMaChuDeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.KhoaHocDTO> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.KhoaHocDTO>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class layTheoMaNguoiDungCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public layTheoMaNguoiDungCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.KhoaHocDTO> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.KhoaHocDTO>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class layTheoMaNguoiDungVaTrangThaiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public layTheoMaNguoiDungVaTrangThaiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.KhoaHocDTO> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.KhoaHocDTO>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class timKiemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public timKiemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.KhoaHocDTO> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.KhoaHocDTO>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class timKiemTheoMaChuDeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public timKiemTheoMaChuDeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.KhoaHocDTO> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.KhoaHocDTO>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Iwcf_KhoaHocClient : System.ServiceModel.ClientBase<ViewModel.wcf_KhoaHoc.Iwcf_KhoaHoc>, ViewModel.wcf_KhoaHoc.Iwcf_KhoaHoc {
        
        private BeginOperationDelegate onBeginlayHinhAnhDelegate;
        
        private EndOperationDelegate onEndlayHinhAnhDelegate;
        
        private System.Threading.SendOrPostCallback onlayHinhAnhCompletedDelegate;
        
        private BeginOperationDelegate onBeginlayHinhAnhChiSoDelegate;
        
        private EndOperationDelegate onEndlayHinhAnhChiSoDelegate;
        
        private System.Threading.SendOrPostCallback onlayHinhAnhChiSoCompletedDelegate;
        
        private BeginOperationDelegate onBeginlayTheoMaDelegate;
        
        private EndOperationDelegate onEndlayTheoMaDelegate;
        
        private System.Threading.SendOrPostCallback onlayTheoMaCompletedDelegate;
        
        private BeginOperationDelegate onBeginlayDelegate;
        
        private EndOperationDelegate onEndlayDelegate;
        
        private System.Threading.SendOrPostCallback onlayCompletedDelegate;
        
        private BeginOperationDelegate onBeginlayTheoMaChuDeDelegate;
        
        private EndOperationDelegate onEndlayTheoMaChuDeDelegate;
        
        private System.Threading.SendOrPostCallback onlayTheoMaChuDeCompletedDelegate;
        
        private BeginOperationDelegate onBeginlayTheoMaNguoiDungDelegate;
        
        private EndOperationDelegate onEndlayTheoMaNguoiDungDelegate;
        
        private System.Threading.SendOrPostCallback onlayTheoMaNguoiDungCompletedDelegate;
        
        private BeginOperationDelegate onBeginlayTheoMaNguoiDungVaTrangThaiDelegate;
        
        private EndOperationDelegate onEndlayTheoMaNguoiDungVaTrangThaiDelegate;
        
        private System.Threading.SendOrPostCallback onlayTheoMaNguoiDungVaTrangThaiCompletedDelegate;
        
        private BeginOperationDelegate onBegintimKiemDelegate;
        
        private EndOperationDelegate onEndtimKiemDelegate;
        
        private System.Threading.SendOrPostCallback ontimKiemCompletedDelegate;
        
        private BeginOperationDelegate onBegintimKiemTheoMaChuDeDelegate;
        
        private EndOperationDelegate onEndtimKiemTheoMaChuDeDelegate;
        
        private System.Threading.SendOrPostCallback ontimKiemTheoMaChuDeCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public Iwcf_KhoaHocClient() {
        }
        
        public Iwcf_KhoaHocClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Iwcf_KhoaHocClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Iwcf_KhoaHocClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Iwcf_KhoaHocClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<layHinhAnhCompletedEventArgs> layHinhAnhCompleted;
        
        public event System.EventHandler<layHinhAnhChiSoCompletedEventArgs> layHinhAnhChiSoCompleted;
        
        public event System.EventHandler<layTheoMaCompletedEventArgs> layTheoMaCompleted;
        
        public event System.EventHandler<layCompletedEventArgs> layCompleted;
        
        public event System.EventHandler<layTheoMaChuDeCompletedEventArgs> layTheoMaChuDeCompleted;
        
        public event System.EventHandler<layTheoMaNguoiDungCompletedEventArgs> layTheoMaNguoiDungCompleted;
        
        public event System.EventHandler<layTheoMaNguoiDungVaTrangThaiCompletedEventArgs> layTheoMaNguoiDungVaTrangThaiCompleted;
        
        public event System.EventHandler<timKiemCompletedEventArgs> timKiemCompleted;
        
        public event System.EventHandler<timKiemTheoMaChuDeCompletedEventArgs> timKiemTheoMaChuDeCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ViewModel.wcf_KhoaHoc.Iwcf_KhoaHoc.BeginlayHinhAnh(string _Ten, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginlayHinhAnh(_Ten, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        byte[] ViewModel.wcf_KhoaHoc.Iwcf_KhoaHoc.EndlayHinhAnh(System.IAsyncResult result) {
            return base.Channel.EndlayHinhAnh(result);
        }
        
        private System.IAsyncResult OnBeginlayHinhAnh(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string _Ten = ((string)(inValues[0]));
            return ((ViewModel.wcf_KhoaHoc.Iwcf_KhoaHoc)(this)).BeginlayHinhAnh(_Ten, callback, asyncState);
        }
        
        private object[] OnEndlayHinhAnh(System.IAsyncResult result) {
            byte[] retVal = ((ViewModel.wcf_KhoaHoc.Iwcf_KhoaHoc)(this)).EndlayHinhAnh(result);
            return new object[] {
                    retVal};
        }
        
        private void OnlayHinhAnhCompleted(object state) {
            if ((this.layHinhAnhCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.layHinhAnhCompleted(this, new layHinhAnhCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void layHinhAnhAsync(string _Ten) {
            this.layHinhAnhAsync(_Ten, null);
        }
        
        public void layHinhAnhAsync(string _Ten, object userState) {
            if ((this.onBeginlayHinhAnhDelegate == null)) {
                this.onBeginlayHinhAnhDelegate = new BeginOperationDelegate(this.OnBeginlayHinhAnh);
            }
            if ((this.onEndlayHinhAnhDelegate == null)) {
                this.onEndlayHinhAnhDelegate = new EndOperationDelegate(this.OnEndlayHinhAnh);
            }
            if ((this.onlayHinhAnhCompletedDelegate == null)) {
                this.onlayHinhAnhCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnlayHinhAnhCompleted);
            }
            base.InvokeAsync(this.onBeginlayHinhAnhDelegate, new object[] {
                        _Ten}, this.onEndlayHinhAnhDelegate, this.onlayHinhAnhCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ViewModel.wcf_KhoaHoc.Iwcf_KhoaHoc.BeginlayHinhAnhChiSo(int _ChiSo, string _Ten, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginlayHinhAnhChiSo(_ChiSo, _Ten, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ViewModel.wcf_KhoaHoc.clientmodel_HinhAnh ViewModel.wcf_KhoaHoc.Iwcf_KhoaHoc.EndlayHinhAnhChiSo(System.IAsyncResult result) {
            return base.Channel.EndlayHinhAnhChiSo(result);
        }
        
        private System.IAsyncResult OnBeginlayHinhAnhChiSo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int _ChiSo = ((int)(inValues[0]));
            string _Ten = ((string)(inValues[1]));
            return ((ViewModel.wcf_KhoaHoc.Iwcf_KhoaHoc)(this)).BeginlayHinhAnhChiSo(_ChiSo, _Ten, callback, asyncState);
        }
        
        private object[] OnEndlayHinhAnhChiSo(System.IAsyncResult result) {
            ViewModel.wcf_KhoaHoc.clientmodel_HinhAnh retVal = ((ViewModel.wcf_KhoaHoc.Iwcf_KhoaHoc)(this)).EndlayHinhAnhChiSo(result);
            return new object[] {
                    retVal};
        }
        
        private void OnlayHinhAnhChiSoCompleted(object state) {
            if ((this.layHinhAnhChiSoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.layHinhAnhChiSoCompleted(this, new layHinhAnhChiSoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void layHinhAnhChiSoAsync(int _ChiSo, string _Ten) {
            this.layHinhAnhChiSoAsync(_ChiSo, _Ten, null);
        }
        
        public void layHinhAnhChiSoAsync(int _ChiSo, string _Ten, object userState) {
            if ((this.onBeginlayHinhAnhChiSoDelegate == null)) {
                this.onBeginlayHinhAnhChiSoDelegate = new BeginOperationDelegate(this.OnBeginlayHinhAnhChiSo);
            }
            if ((this.onEndlayHinhAnhChiSoDelegate == null)) {
                this.onEndlayHinhAnhChiSoDelegate = new EndOperationDelegate(this.OnEndlayHinhAnhChiSo);
            }
            if ((this.onlayHinhAnhChiSoCompletedDelegate == null)) {
                this.onlayHinhAnhChiSoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnlayHinhAnhChiSoCompleted);
            }
            base.InvokeAsync(this.onBeginlayHinhAnhChiSoDelegate, new object[] {
                        _ChiSo,
                        _Ten}, this.onEndlayHinhAnhChiSoDelegate, this.onlayHinhAnhChiSoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ViewModel.wcf_KhoaHoc.Iwcf_KhoaHoc.BeginlayTheoMa(int _Ma, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginlayTheoMa(_Ma, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ViewModel.wcf_KhoaHoc.KhoaHocDTO ViewModel.wcf_KhoaHoc.Iwcf_KhoaHoc.EndlayTheoMa(System.IAsyncResult result) {
            return base.Channel.EndlayTheoMa(result);
        }
        
        private System.IAsyncResult OnBeginlayTheoMa(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int _Ma = ((int)(inValues[0]));
            return ((ViewModel.wcf_KhoaHoc.Iwcf_KhoaHoc)(this)).BeginlayTheoMa(_Ma, callback, asyncState);
        }
        
        private object[] OnEndlayTheoMa(System.IAsyncResult result) {
            ViewModel.wcf_KhoaHoc.KhoaHocDTO retVal = ((ViewModel.wcf_KhoaHoc.Iwcf_KhoaHoc)(this)).EndlayTheoMa(result);
            return new object[] {
                    retVal};
        }
        
        private void OnlayTheoMaCompleted(object state) {
            if ((this.layTheoMaCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.layTheoMaCompleted(this, new layTheoMaCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void layTheoMaAsync(int _Ma) {
            this.layTheoMaAsync(_Ma, null);
        }
        
        public void layTheoMaAsync(int _Ma, object userState) {
            if ((this.onBeginlayTheoMaDelegate == null)) {
                this.onBeginlayTheoMaDelegate = new BeginOperationDelegate(this.OnBeginlayTheoMa);
            }
            if ((this.onEndlayTheoMaDelegate == null)) {
                this.onEndlayTheoMaDelegate = new EndOperationDelegate(this.OnEndlayTheoMa);
            }
            if ((this.onlayTheoMaCompletedDelegate == null)) {
                this.onlayTheoMaCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnlayTheoMaCompleted);
            }
            base.InvokeAsync(this.onBeginlayTheoMaDelegate, new object[] {
                        _Ma}, this.onEndlayTheoMaDelegate, this.onlayTheoMaCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ViewModel.wcf_KhoaHoc.Iwcf_KhoaHoc.Beginlay(System.AsyncCallback callback, object asyncState) {
            return base.Channel.Beginlay(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.KhoaHocDTO> ViewModel.wcf_KhoaHoc.Iwcf_KhoaHoc.Endlay(System.IAsyncResult result) {
            return base.Channel.Endlay(result);
        }
        
        private System.IAsyncResult OnBeginlay(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((ViewModel.wcf_KhoaHoc.Iwcf_KhoaHoc)(this)).Beginlay(callback, asyncState);
        }
        
        private object[] OnEndlay(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.KhoaHocDTO> retVal = ((ViewModel.wcf_KhoaHoc.Iwcf_KhoaHoc)(this)).Endlay(result);
            return new object[] {
                    retVal};
        }
        
        private void OnlayCompleted(object state) {
            if ((this.layCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.layCompleted(this, new layCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void layAsync() {
            this.layAsync(null);
        }
        
        public void layAsync(object userState) {
            if ((this.onBeginlayDelegate == null)) {
                this.onBeginlayDelegate = new BeginOperationDelegate(this.OnBeginlay);
            }
            if ((this.onEndlayDelegate == null)) {
                this.onEndlayDelegate = new EndOperationDelegate(this.OnEndlay);
            }
            if ((this.onlayCompletedDelegate == null)) {
                this.onlayCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnlayCompleted);
            }
            base.InvokeAsync(this.onBeginlayDelegate, null, this.onEndlayDelegate, this.onlayCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ViewModel.wcf_KhoaHoc.Iwcf_KhoaHoc.BeginlayTheoMaChuDe(int _MaChuDe, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginlayTheoMaChuDe(_MaChuDe, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.KhoaHocDTO> ViewModel.wcf_KhoaHoc.Iwcf_KhoaHoc.EndlayTheoMaChuDe(System.IAsyncResult result) {
            return base.Channel.EndlayTheoMaChuDe(result);
        }
        
        private System.IAsyncResult OnBeginlayTheoMaChuDe(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int _MaChuDe = ((int)(inValues[0]));
            return ((ViewModel.wcf_KhoaHoc.Iwcf_KhoaHoc)(this)).BeginlayTheoMaChuDe(_MaChuDe, callback, asyncState);
        }
        
        private object[] OnEndlayTheoMaChuDe(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.KhoaHocDTO> retVal = ((ViewModel.wcf_KhoaHoc.Iwcf_KhoaHoc)(this)).EndlayTheoMaChuDe(result);
            return new object[] {
                    retVal};
        }
        
        private void OnlayTheoMaChuDeCompleted(object state) {
            if ((this.layTheoMaChuDeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.layTheoMaChuDeCompleted(this, new layTheoMaChuDeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void layTheoMaChuDeAsync(int _MaChuDe) {
            this.layTheoMaChuDeAsync(_MaChuDe, null);
        }
        
        public void layTheoMaChuDeAsync(int _MaChuDe, object userState) {
            if ((this.onBeginlayTheoMaChuDeDelegate == null)) {
                this.onBeginlayTheoMaChuDeDelegate = new BeginOperationDelegate(this.OnBeginlayTheoMaChuDe);
            }
            if ((this.onEndlayTheoMaChuDeDelegate == null)) {
                this.onEndlayTheoMaChuDeDelegate = new EndOperationDelegate(this.OnEndlayTheoMaChuDe);
            }
            if ((this.onlayTheoMaChuDeCompletedDelegate == null)) {
                this.onlayTheoMaChuDeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnlayTheoMaChuDeCompleted);
            }
            base.InvokeAsync(this.onBeginlayTheoMaChuDeDelegate, new object[] {
                        _MaChuDe}, this.onEndlayTheoMaChuDeDelegate, this.onlayTheoMaChuDeCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ViewModel.wcf_KhoaHoc.Iwcf_KhoaHoc.BeginlayTheoMaNguoiDung(int _MaNguoiDung, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginlayTheoMaNguoiDung(_MaNguoiDung, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.KhoaHocDTO> ViewModel.wcf_KhoaHoc.Iwcf_KhoaHoc.EndlayTheoMaNguoiDung(System.IAsyncResult result) {
            return base.Channel.EndlayTheoMaNguoiDung(result);
        }
        
        private System.IAsyncResult OnBeginlayTheoMaNguoiDung(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int _MaNguoiDung = ((int)(inValues[0]));
            return ((ViewModel.wcf_KhoaHoc.Iwcf_KhoaHoc)(this)).BeginlayTheoMaNguoiDung(_MaNguoiDung, callback, asyncState);
        }
        
        private object[] OnEndlayTheoMaNguoiDung(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.KhoaHocDTO> retVal = ((ViewModel.wcf_KhoaHoc.Iwcf_KhoaHoc)(this)).EndlayTheoMaNguoiDung(result);
            return new object[] {
                    retVal};
        }
        
        private void OnlayTheoMaNguoiDungCompleted(object state) {
            if ((this.layTheoMaNguoiDungCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.layTheoMaNguoiDungCompleted(this, new layTheoMaNguoiDungCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void layTheoMaNguoiDungAsync(int _MaNguoiDung) {
            this.layTheoMaNguoiDungAsync(_MaNguoiDung, null);
        }
        
        public void layTheoMaNguoiDungAsync(int _MaNguoiDung, object userState) {
            if ((this.onBeginlayTheoMaNguoiDungDelegate == null)) {
                this.onBeginlayTheoMaNguoiDungDelegate = new BeginOperationDelegate(this.OnBeginlayTheoMaNguoiDung);
            }
            if ((this.onEndlayTheoMaNguoiDungDelegate == null)) {
                this.onEndlayTheoMaNguoiDungDelegate = new EndOperationDelegate(this.OnEndlayTheoMaNguoiDung);
            }
            if ((this.onlayTheoMaNguoiDungCompletedDelegate == null)) {
                this.onlayTheoMaNguoiDungCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnlayTheoMaNguoiDungCompleted);
            }
            base.InvokeAsync(this.onBeginlayTheoMaNguoiDungDelegate, new object[] {
                        _MaNguoiDung}, this.onEndlayTheoMaNguoiDungDelegate, this.onlayTheoMaNguoiDungCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ViewModel.wcf_KhoaHoc.Iwcf_KhoaHoc.BeginlayTheoMaNguoiDungVaTrangThai(int _MaNguoiDung, int _TrangThai, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginlayTheoMaNguoiDungVaTrangThai(_MaNguoiDung, _TrangThai, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.KhoaHocDTO> ViewModel.wcf_KhoaHoc.Iwcf_KhoaHoc.EndlayTheoMaNguoiDungVaTrangThai(System.IAsyncResult result) {
            return base.Channel.EndlayTheoMaNguoiDungVaTrangThai(result);
        }
        
        private System.IAsyncResult OnBeginlayTheoMaNguoiDungVaTrangThai(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int _MaNguoiDung = ((int)(inValues[0]));
            int _TrangThai = ((int)(inValues[1]));
            return ((ViewModel.wcf_KhoaHoc.Iwcf_KhoaHoc)(this)).BeginlayTheoMaNguoiDungVaTrangThai(_MaNguoiDung, _TrangThai, callback, asyncState);
        }
        
        private object[] OnEndlayTheoMaNguoiDungVaTrangThai(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.KhoaHocDTO> retVal = ((ViewModel.wcf_KhoaHoc.Iwcf_KhoaHoc)(this)).EndlayTheoMaNguoiDungVaTrangThai(result);
            return new object[] {
                    retVal};
        }
        
        private void OnlayTheoMaNguoiDungVaTrangThaiCompleted(object state) {
            if ((this.layTheoMaNguoiDungVaTrangThaiCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.layTheoMaNguoiDungVaTrangThaiCompleted(this, new layTheoMaNguoiDungVaTrangThaiCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void layTheoMaNguoiDungVaTrangThaiAsync(int _MaNguoiDung, int _TrangThai) {
            this.layTheoMaNguoiDungVaTrangThaiAsync(_MaNguoiDung, _TrangThai, null);
        }
        
        public void layTheoMaNguoiDungVaTrangThaiAsync(int _MaNguoiDung, int _TrangThai, object userState) {
            if ((this.onBeginlayTheoMaNguoiDungVaTrangThaiDelegate == null)) {
                this.onBeginlayTheoMaNguoiDungVaTrangThaiDelegate = new BeginOperationDelegate(this.OnBeginlayTheoMaNguoiDungVaTrangThai);
            }
            if ((this.onEndlayTheoMaNguoiDungVaTrangThaiDelegate == null)) {
                this.onEndlayTheoMaNguoiDungVaTrangThaiDelegate = new EndOperationDelegate(this.OnEndlayTheoMaNguoiDungVaTrangThai);
            }
            if ((this.onlayTheoMaNguoiDungVaTrangThaiCompletedDelegate == null)) {
                this.onlayTheoMaNguoiDungVaTrangThaiCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnlayTheoMaNguoiDungVaTrangThaiCompleted);
            }
            base.InvokeAsync(this.onBeginlayTheoMaNguoiDungVaTrangThaiDelegate, new object[] {
                        _MaNguoiDung,
                        _TrangThai}, this.onEndlayTheoMaNguoiDungVaTrangThaiDelegate, this.onlayTheoMaNguoiDungVaTrangThaiCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ViewModel.wcf_KhoaHoc.Iwcf_KhoaHoc.BegintimKiem(string _TuKhoa, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegintimKiem(_TuKhoa, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.KhoaHocDTO> ViewModel.wcf_KhoaHoc.Iwcf_KhoaHoc.EndtimKiem(System.IAsyncResult result) {
            return base.Channel.EndtimKiem(result);
        }
        
        private System.IAsyncResult OnBegintimKiem(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string _TuKhoa = ((string)(inValues[0]));
            return ((ViewModel.wcf_KhoaHoc.Iwcf_KhoaHoc)(this)).BegintimKiem(_TuKhoa, callback, asyncState);
        }
        
        private object[] OnEndtimKiem(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.KhoaHocDTO> retVal = ((ViewModel.wcf_KhoaHoc.Iwcf_KhoaHoc)(this)).EndtimKiem(result);
            return new object[] {
                    retVal};
        }
        
        private void OntimKiemCompleted(object state) {
            if ((this.timKiemCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.timKiemCompleted(this, new timKiemCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void timKiemAsync(string _TuKhoa) {
            this.timKiemAsync(_TuKhoa, null);
        }
        
        public void timKiemAsync(string _TuKhoa, object userState) {
            if ((this.onBegintimKiemDelegate == null)) {
                this.onBegintimKiemDelegate = new BeginOperationDelegate(this.OnBegintimKiem);
            }
            if ((this.onEndtimKiemDelegate == null)) {
                this.onEndtimKiemDelegate = new EndOperationDelegate(this.OnEndtimKiem);
            }
            if ((this.ontimKiemCompletedDelegate == null)) {
                this.ontimKiemCompletedDelegate = new System.Threading.SendOrPostCallback(this.OntimKiemCompleted);
            }
            base.InvokeAsync(this.onBegintimKiemDelegate, new object[] {
                        _TuKhoa}, this.onEndtimKiemDelegate, this.ontimKiemCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ViewModel.wcf_KhoaHoc.Iwcf_KhoaHoc.BegintimKiemTheoMaChuDe(int _MaChuDe, string _TuKhoa, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegintimKiemTheoMaChuDe(_MaChuDe, _TuKhoa, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.KhoaHocDTO> ViewModel.wcf_KhoaHoc.Iwcf_KhoaHoc.EndtimKiemTheoMaChuDe(System.IAsyncResult result) {
            return base.Channel.EndtimKiemTheoMaChuDe(result);
        }
        
        private System.IAsyncResult OnBegintimKiemTheoMaChuDe(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int _MaChuDe = ((int)(inValues[0]));
            string _TuKhoa = ((string)(inValues[1]));
            return ((ViewModel.wcf_KhoaHoc.Iwcf_KhoaHoc)(this)).BegintimKiemTheoMaChuDe(_MaChuDe, _TuKhoa, callback, asyncState);
        }
        
        private object[] OnEndtimKiemTheoMaChuDe(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.KhoaHocDTO> retVal = ((ViewModel.wcf_KhoaHoc.Iwcf_KhoaHoc)(this)).EndtimKiemTheoMaChuDe(result);
            return new object[] {
                    retVal};
        }
        
        private void OntimKiemTheoMaChuDeCompleted(object state) {
            if ((this.timKiemTheoMaChuDeCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.timKiemTheoMaChuDeCompleted(this, new timKiemTheoMaChuDeCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void timKiemTheoMaChuDeAsync(int _MaChuDe, string _TuKhoa) {
            this.timKiemTheoMaChuDeAsync(_MaChuDe, _TuKhoa, null);
        }
        
        public void timKiemTheoMaChuDeAsync(int _MaChuDe, string _TuKhoa, object userState) {
            if ((this.onBegintimKiemTheoMaChuDeDelegate == null)) {
                this.onBegintimKiemTheoMaChuDeDelegate = new BeginOperationDelegate(this.OnBegintimKiemTheoMaChuDe);
            }
            if ((this.onEndtimKiemTheoMaChuDeDelegate == null)) {
                this.onEndtimKiemTheoMaChuDeDelegate = new EndOperationDelegate(this.OnEndtimKiemTheoMaChuDe);
            }
            if ((this.ontimKiemTheoMaChuDeCompletedDelegate == null)) {
                this.ontimKiemTheoMaChuDeCompletedDelegate = new System.Threading.SendOrPostCallback(this.OntimKiemTheoMaChuDeCompleted);
            }
            base.InvokeAsync(this.onBegintimKiemTheoMaChuDeDelegate, new object[] {
                        _MaChuDe,
                        _TuKhoa}, this.onEndtimKiemTheoMaChuDeDelegate, this.ontimKiemTheoMaChuDeCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override ViewModel.wcf_KhoaHoc.Iwcf_KhoaHoc CreateChannel() {
            return new Iwcf_KhoaHocClientChannel(this);
        }
        
        private class Iwcf_KhoaHocClientChannel : ChannelBase<ViewModel.wcf_KhoaHoc.Iwcf_KhoaHoc>, ViewModel.wcf_KhoaHoc.Iwcf_KhoaHoc {
            
            public Iwcf_KhoaHocClientChannel(System.ServiceModel.ClientBase<ViewModel.wcf_KhoaHoc.Iwcf_KhoaHoc> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginlayHinhAnh(string _Ten, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = _Ten;
                System.IAsyncResult _result = base.BeginInvoke("layHinhAnh", _args, callback, asyncState);
                return _result;
            }
            
            public byte[] EndlayHinhAnh(System.IAsyncResult result) {
                object[] _args = new object[0];
                byte[] _result = ((byte[])(base.EndInvoke("layHinhAnh", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginlayHinhAnhChiSo(int _ChiSo, string _Ten, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = _ChiSo;
                _args[1] = _Ten;
                System.IAsyncResult _result = base.BeginInvoke("layHinhAnhChiSo", _args, callback, asyncState);
                return _result;
            }
            
            public ViewModel.wcf_KhoaHoc.clientmodel_HinhAnh EndlayHinhAnhChiSo(System.IAsyncResult result) {
                object[] _args = new object[0];
                ViewModel.wcf_KhoaHoc.clientmodel_HinhAnh _result = ((ViewModel.wcf_KhoaHoc.clientmodel_HinhAnh)(base.EndInvoke("layHinhAnhChiSo", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginlayTheoMa(int _Ma, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = _Ma;
                System.IAsyncResult _result = base.BeginInvoke("layTheoMa", _args, callback, asyncState);
                return _result;
            }
            
            public ViewModel.wcf_KhoaHoc.KhoaHocDTO EndlayTheoMa(System.IAsyncResult result) {
                object[] _args = new object[0];
                ViewModel.wcf_KhoaHoc.KhoaHocDTO _result = ((ViewModel.wcf_KhoaHoc.KhoaHocDTO)(base.EndInvoke("layTheoMa", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult Beginlay(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("lay", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.KhoaHocDTO> Endlay(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.KhoaHocDTO> _result = ((System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.KhoaHocDTO>)(base.EndInvoke("lay", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginlayTheoMaChuDe(int _MaChuDe, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = _MaChuDe;
                System.IAsyncResult _result = base.BeginInvoke("layTheoMaChuDe", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.KhoaHocDTO> EndlayTheoMaChuDe(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.KhoaHocDTO> _result = ((System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.KhoaHocDTO>)(base.EndInvoke("layTheoMaChuDe", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginlayTheoMaNguoiDung(int _MaNguoiDung, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = _MaNguoiDung;
                System.IAsyncResult _result = base.BeginInvoke("layTheoMaNguoiDung", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.KhoaHocDTO> EndlayTheoMaNguoiDung(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.KhoaHocDTO> _result = ((System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.KhoaHocDTO>)(base.EndInvoke("layTheoMaNguoiDung", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginlayTheoMaNguoiDungVaTrangThai(int _MaNguoiDung, int _TrangThai, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = _MaNguoiDung;
                _args[1] = _TrangThai;
                System.IAsyncResult _result = base.BeginInvoke("layTheoMaNguoiDungVaTrangThai", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.KhoaHocDTO> EndlayTheoMaNguoiDungVaTrangThai(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.KhoaHocDTO> _result = ((System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.KhoaHocDTO>)(base.EndInvoke("layTheoMaNguoiDungVaTrangThai", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegintimKiem(string _TuKhoa, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = _TuKhoa;
                System.IAsyncResult _result = base.BeginInvoke("timKiem", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.KhoaHocDTO> EndtimKiem(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.KhoaHocDTO> _result = ((System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.KhoaHocDTO>)(base.EndInvoke("timKiem", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegintimKiemTheoMaChuDe(int _MaChuDe, string _TuKhoa, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = _MaChuDe;
                _args[1] = _TuKhoa;
                System.IAsyncResult _result = base.BeginInvoke("timKiemTheoMaChuDe", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.KhoaHocDTO> EndtimKiemTheoMaChuDe(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.KhoaHocDTO> _result = ((System.Collections.ObjectModel.ObservableCollection<ViewModel.wcf_KhoaHoc.KhoaHocDTO>)(base.EndInvoke("timKiemTheoMaChuDe", _args, result)));
                return _result;
            }
        }
    }
}
