//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace ViewModel.wcf_NguoiDung {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wcf_NguoiDung.Iwcf_NguoiDung")]
    public interface Iwcf_NguoiDung {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Iwcf_NguoiDung/kiemTraDangNhap", ReplyAction="http://tempuri.org/Iwcf_NguoiDung/kiemTraDangNhapResponse")]
        System.IAsyncResult BeginkiemTraDangNhap(string _TenDN, string _MatKhau, System.AsyncCallback callback, object asyncState);
        
        int EndkiemTraDangNhap(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Iwcf_NguoiDungChannel : ViewModel.wcf_NguoiDung.Iwcf_NguoiDung, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class kiemTraDangNhapCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public kiemTraDangNhapCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Iwcf_NguoiDungClient : System.ServiceModel.ClientBase<ViewModel.wcf_NguoiDung.Iwcf_NguoiDung>, ViewModel.wcf_NguoiDung.Iwcf_NguoiDung {
        
        private BeginOperationDelegate onBeginkiemTraDangNhapDelegate;
        
        private EndOperationDelegate onEndkiemTraDangNhapDelegate;
        
        private System.Threading.SendOrPostCallback onkiemTraDangNhapCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public Iwcf_NguoiDungClient() {
        }
        
        public Iwcf_NguoiDungClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Iwcf_NguoiDungClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Iwcf_NguoiDungClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Iwcf_NguoiDungClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<kiemTraDangNhapCompletedEventArgs> kiemTraDangNhapCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult ViewModel.wcf_NguoiDung.Iwcf_NguoiDung.BeginkiemTraDangNhap(string _TenDN, string _MatKhau, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginkiemTraDangNhap(_TenDN, _MatKhau, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int ViewModel.wcf_NguoiDung.Iwcf_NguoiDung.EndkiemTraDangNhap(System.IAsyncResult result) {
            return base.Channel.EndkiemTraDangNhap(result);
        }
        
        private System.IAsyncResult OnBeginkiemTraDangNhap(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string _TenDN = ((string)(inValues[0]));
            string _MatKhau = ((string)(inValues[1]));
            return ((ViewModel.wcf_NguoiDung.Iwcf_NguoiDung)(this)).BeginkiemTraDangNhap(_TenDN, _MatKhau, callback, asyncState);
        }
        
        private object[] OnEndkiemTraDangNhap(System.IAsyncResult result) {
            int retVal = ((ViewModel.wcf_NguoiDung.Iwcf_NguoiDung)(this)).EndkiemTraDangNhap(result);
            return new object[] {
                    retVal};
        }
        
        private void OnkiemTraDangNhapCompleted(object state) {
            if ((this.kiemTraDangNhapCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.kiemTraDangNhapCompleted(this, new kiemTraDangNhapCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void kiemTraDangNhapAsync(string _TenDN, string _MatKhau) {
            this.kiemTraDangNhapAsync(_TenDN, _MatKhau, null);
        }
        
        public void kiemTraDangNhapAsync(string _TenDN, string _MatKhau, object userState) {
            if ((this.onBeginkiemTraDangNhapDelegate == null)) {
                this.onBeginkiemTraDangNhapDelegate = new BeginOperationDelegate(this.OnBeginkiemTraDangNhap);
            }
            if ((this.onEndkiemTraDangNhapDelegate == null)) {
                this.onEndkiemTraDangNhapDelegate = new EndOperationDelegate(this.OnEndkiemTraDangNhap);
            }
            if ((this.onkiemTraDangNhapCompletedDelegate == null)) {
                this.onkiemTraDangNhapCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnkiemTraDangNhapCompleted);
            }
            base.InvokeAsync(this.onBeginkiemTraDangNhapDelegate, new object[] {
                        _TenDN,
                        _MatKhau}, this.onEndkiemTraDangNhapDelegate, this.onkiemTraDangNhapCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override ViewModel.wcf_NguoiDung.Iwcf_NguoiDung CreateChannel() {
            return new Iwcf_NguoiDungClientChannel(this);
        }
        
        private class Iwcf_NguoiDungClientChannel : ChannelBase<ViewModel.wcf_NguoiDung.Iwcf_NguoiDung>, ViewModel.wcf_NguoiDung.Iwcf_NguoiDung {
            
            public Iwcf_NguoiDungClientChannel(System.ServiceModel.ClientBase<ViewModel.wcf_NguoiDung.Iwcf_NguoiDung> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginkiemTraDangNhap(string _TenDN, string _MatKhau, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = _TenDN;
                _args[1] = _MatKhau;
                System.IAsyncResult _result = base.BeginInvoke("kiemTraDangNhap", _args, callback, asyncState);
                return _result;
            }
            
            public int EndkiemTraDangNhap(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("kiemTraDangNhap", _args, result)));
                return _result;
            }
        }
    }
}
